config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  devise_for :users,
    path: '',
    path_names: {sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'registration'},
    controllers: {omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations'}

  resources :rooms do 
    member do
      get 'listing'
      get 'price'
      get 'description'
      get 'photo_upload'
      get 'amenity'
      get 'location'
      get 'preload'
      get 'preview'
    end
    resources :photos, only: [:create, :destroy]
    resources :reservations, only: [:create]
  end

  get '/reservations', to: "reservations#your_reservations"
  get '/trips', to:"reservations#your_trips"

  resources :users, only: [:show]

  resources :guest_reviews, only: [:create, :destroy]
  resources :host_reviews, only: [:create, :destroy]

  get 'search' => 'pages#search'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :room
  belongs_to :user
end

app/controllers/reservation_controller.rb
class ReservationController < ApplicationController

  def create
    @room = Room.find(params[:room_id])

    if current_user == @room.current_user
      flash[:alert] = "You cannot book your own property!"
    else
      start_date = Date.parse(reservation_params[:start_date])
      end_date = Date.parse(reservation_params[:end_date])
      nights = (end_date - start_date).to_i

      @reservation = current_user.reservations.new(reservarion_params)
      @reservation.room = @room
      @reservation.price_per_night = @room.price
      @reservation.total_price = @room.price * nights
      @reservation.save

      flash[:success] = "Successfully Booked Room!"


    end

    redirect_to room_url(@room)
  end

  private
    def reservation_params
      params.require(:reservation).permit(:start_date, :end_date)
    end

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

  def create
    @room = Room.find(params[:room_id])

    if current_user == @room.user
      flash[:alert] = "You cannot book your own property!"
    else
      start_date = Date.parse(reservation_params[:start_date])
      end_date = Date.parse(reservation_params[:end_date])
      nights = (end_date - start_date).to_i

      @reservation = current_user.reservations.new(reservation_params)
      @reservation.room = @room
      @reservation.price_per_night = @room.price
      @reservation.total_price = @room.price * nights
      @reservation.save

      flash[:success] = "Successfully Booked Room!"


    end

    redirect_to room_url(@room)
  end

  def your_reservations
    @rooms = current_user.rooms
  end

  def your_trips
    @reservations = current_user.reservations
  end
  

  private
    def reservation_params
      params.require(:reservation).permit(:start_date, :end_date)
    end

end

app/helpers/reservation_helper.rb
module ReservationHelper
end

app/views/reservations/_sidebar.html.erb
<div class="card mt-3">
    <div class="card-body">
        <p><strong><%= link_to "•Your Listing",rooms_path, class: "sidelink" %>
        <p><%= link_to "•Your Reservations",reservations_path, class: "sidelink" %>
        <p class="mb-0"><%= link_to "•Your Trips",trips_path, class: "sidelink" %></strong>
    </div>
</div>

app/views/reservations/your_reservations.html.erb
<div class=" container editprofile mt-2 pb-4">
    <div class="row">
        <div class="col-md-4">
            <%= render "reservations/sidebar"%>
        </div>
        <div class="col-md-4">
            <div class="card mt-3" style="width: 50rem;">
                <strong><div class="card-header bg-success text-light text-center"></strong>
                    Your Reservations
                </div>
                <div class="card-body">
                    <% @rooms.each do |room| %>
                        <% room.reservations.each do |reservation| %>
                        <div class="row">
                            <div class="col-3">
                                <%= reservation.start_date.strftime('%v') %>
                            </div>
                            <div class="col-2">
                                <% if reservation.room.photos.any? %>
                                    <%= image_tag reservation.room.photos.first.image.url, class: "mr-5 profile_picture_index" %>
                                <% else %>
                                    <%= image_tag "no-image.png", class: "mr-5 profile_picture_index2"  %>
                                <% end %>
                            </div>
                            <div class="col-5">
                                <%= reservation.room.name %>
                                <%= image_tag avatar_url(reservation.user), class: "rounded-circle profile_picture mx-3" %>
                                <%= reservation.user.name %>
                            </div>
                            <div class="col-2">
                                <%= render partial: "reviews/host_form", locals: {reservation: reservation} %>
                                <%# <%= link_to "Review Guest","#", class: "btn btn-outline-success" %>
                            </div>
                        </div>
                        <div class="border-bottom my-3"></div>
                        <% end %>
                    <% end %>
                </div>
                <%# <div class="pagenate mt-1 text-center"><%= will_paginate %>
            </div>  
        </div>
    </div>
</div>

app/views/reservations/your_trips.html.erb
<div class="container editprofile mt-2 pb-4">
    <div class="row">
        <div class="col-md-4">
            <%= render "reservations/sidebar"%>
        </div>
        <div class="col-md-4">
            <div class="card mt-3" style="width: 50rem;">
                <strong><div class="card-header bg-success text-light text-center"></strong>
                    Your Trips
                </div>
                <div class="card-body">
                    <% @reservations.each do |reservation| %>
                    <div class="row">
                        <div class="col-3">
                            <%= reservation.start_date.strftime('%v') %>
                        </div>
                        <div class="col-2">
                            <% if reservation.room.photos.any? %>
                                <%= image_tag reservation.room.photos.first.image.url, class: "mr-5 profile_picture_index" %>
                            <% else %>
                                <%= image_tag "no-image.png", class: "profile_picture_index2" %>
                            <% end %>
                        </div>
                        <div class="col-5">
                            <%= reservation.room.name %>
                            <%= image_tag avatar_url(reservation.room.user), class: "rounded-circle profile_picture mx-2" %>
                            <%= reservation.room.user.name %>
                        </div>
                        <div class="col-2">
                            <%= render partial: "reviews/guest_form", locals: {reservation: reservation} %>
                            <%# <%= link_to "Review host","#", class: "btn btn-outline-success" %>
                        </div>
                    </div>
                    <div class="border-bottom my-3"></div>
                    <% end %>   
                </div>    
            </div>
        </div>
    </div>
</div>