config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  devise_for :users,
    path: '',
    path_names: {sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'registration'},
    controllers: {omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations'}

  resources :rooms do 
    member do
      get 'listing'
      get 'price'
      get 'description'
      get 'photo_upload'
      get 'amenity'
      get 'location'
      get 'preload'
      get 'preview'
    end
    resources :photos, only: [:create, :destroy]
    resources :reservations, only: [:create]
  end

  get '/reservations', to: "reservations#your_reservations"
  get '/trips', to:"reservations#your_trips"

  resources :users, only: [:show]

  resources :guest_reviews, only: [:create, :destroy]
  resources :host_reviews, only: [:create, :destroy]

  get 'search' => 'pages#search'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  has_many :photos

  validates :home_type, presence: true
  validates :room_type, presence: true
  validates :gest_count, presence: true
  validates :bedroom_count, presence: true
  validates :bathroom_count, presence: true

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  has_many :reservations

  has_many :guest_reviews
  
  def average_rating
    guest_reviews.count == 0 ? 0 : guest_reviews.average(:star).round(2).to_i
  end

  def cover_photo(size)
    if self.photos.length > 0
      self.photos[0].image.url(size)
    else
      "blank.jpg"
    end
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, except: [:index, :new, :create, :autocomplete_room_address]
  before_action :authenticate_user!, except: [:show, :autocomplete_room_address]
  before_action :is_authorized, only: [:listing, :pricing, :description, 
                                      :photo_upload, :amenities, :location, :update]
  autocomplete :room, :address, full: true, where: {active: 1}, unique: true
  
  def new
    @room = current_user.rooms.new
  end

  def index
    # @rooms = current_user.rooms
    @rooms = current_user.rooms.paginate(page: params[:page], per_page: 5)
  end

  def show
    @photos = @room.photos
    @guest_reviews = @room.guest_reviews
  end

  def create
    @room = current_user.rooms.new(room_params)
    if @room.save
      redirect_to listing_room_url(@room)
    else
      render 'new'
    end
  end

  def update
    final_params = is_not_ready?(@room) ? room_params : room_params.merge(is_active: true)  
    if @room.update(final_params)
      flash[:notice] = "Successfully updated!"
    else
      flash[:notice] = "Failed to update!"
    end

    redirect_back(fallback_location: request.referer)
  end

  def listing
  end

  def price
  end

  def description
  end

  def photo_upload
    @photos = @room.photos
  end

  def amenity
  end

  def location
  end

  def preload
    today = Date.today
    reservations = @room.reservations.where("start_date >= ? OR end_date >= ?", today,today)
  
    render json: reservations
  end

  def preview
    start_date = Date.parse(params[:start_date])
    end_date = Date.parse(params[:end_date])

    output = {
      conflict: is_conflict(start_date, end_date, @room)
    }

    render json: output
  end


  private
    def is_conflict(start_date, end_date, room)
      check = room.reservations.where("? < start_date AND end_date < ?", start_date, end_date)
      check.size > 0 ? true : false
    end

    def set_room
      @room = Room.find(params[:id])
    end

    def is_authorized
      redirect_to root_path, alert: "You don't have permission" unless current_user.id == @room.user_id
    end

    def is_ready_room
      !@room.active && !@room.price.blank? && !@room.listing_name.blank? && !@room.photos.blank? && !@room.address.blank?
    end

    def room_params
      params.require(:room).permit(:name, :home_type, :room_type, :gest_count, :bedroom_count, :bathroom_count, :price, :summary, :is_activity, :address, :has_TV, :has_kitchen, :has_internet, :has_heating, :has_air_conditioning)
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
  def  is_done?(item)
    unless item.blank?
      content_tag :span, class: "" do
        content_tag :i, nil, class: "fa fa-check float-right"
      end
    end
  end

  def is_not_ready?(room)
    room.price.blank? || room.name.blank? || room.photos.blank? || room.address.blank?
  end
end

app/views/rooms/_rooms_list.html.erb
<% rooms.each do |room| %>
    <div class="col-md-4">
        <div class="card">
            <div class="card-header search">
                <%= image_tag room.cover_photo(:medium) %>
            </div>
            <div class="card-body">
                <%= link_to room.name, room %><br/>
                $<%= room.price %> - <%= room.home_type %> - <%= pluralize(room.bedroom_count, "bed") %>
                <div id="star_<%= room.id %>"></div><%= pluralize(room.average_rating, "review") %>
            </div>
        </div>
    </div>

    <script>
        $('#star_<%= room.id %>').raty({
            path: '/assets',
            readOnly: true,
            score: <%= room.average_rating %>
        });
    </script>
<% end %>

app/views/rooms/_sidebar.html.erb
<div class="card mt-3">
    <div class="card-body p-3">
        <p><%= link_to "Listing", listing_room_path, class: "sidelink" %><span><i class="fa fa-check float-right"></i></span></p>
        <p><%= link_to "Price", price_room_path, class: "sidelink"%><%= is_done?(@room.price) %></p>
        <p><%= link_to "Description", description_room_path, class: "sidelink" %><%= is_done?(@room.name) %></p>
        <p><%= link_to "Photos", photo_upload_room_path, class: "sidelink" %><%= is_done?(@room.photos) %></p>
        <p><%= link_to "Amenities", amenity_room_path, class: "sidelink" %><span><i class="fa fa-check float-right"></i></span></p>
        <p><%= link_to "Location", location_room_path, class: "sidelink" %><%= is_done?(@room.address) %></p>
        <%# <p class="mb-1"><%= link_to "Location", location_room_path(current_user), class: "sidelink" %><%# <i class="fa fa-times-circle float-right"></i></p> %>
        <div class="dropdown-divider"></div>
        <div class="col-md-6 offset-md-3 mt-3">
            <%= form_for @room do |f| %>
                <%= f.hidden_field :is_active, value: true %>
                <%= f.submit "Publish", class: "btn btn-outline-success", disabled: is_not_ready?(@room) %>
            <% end %>
        </div>
    </div>
</div>

app/views/rooms/amenity.html.erb
<div class="container  mt-3 pb-4">
    <div class="row">
        <div class="col-md-3">
            <%= render "rooms/sidebar"%>
        </div>
        <div class="col-md-4">
            <div class="card mt-3" style="width: 50rem;">
                <strong>
                    <div class="card-header bg-success text-light">
                    Amenities
                    </div>
                <strong>
                <div class="p-4">
                    <%= form_for @room do |f| %>
                        <div class="row">
                            <div class="col-4">
                                <div class="form-group">
                                    <%= f.label :TV %>
                                    <%= f.check_box :has_TV %>
                                </div>
                            </div>
                            <div class="col-4">
                                <div class="form-group">
                                    <%= f.label :Kitchen %>
                                    <%= f.check_box :has_kitchen %>
                                </div>
                            </div>
                            <div class="col-4">
                                <div class="form-group">
                                    <%= f.label :Internet %>
                                    <%= f.check_box :has_internet %>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-4">
                                <div class="form-group">
                                    <%= f.label :Heating %>
                                    <%= f.check_box :has_heating %>
                                </div>
                            </div>
                            <div class="col-4">
                                <div class="form-group">
                                    <%= f.label :Airconditioning %>
                                    <%= f.check_box :has_air_conditioning %>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <%= f.submit "Save", class: "btn btn-outline-success my-2 my-sm-0 ml-3" %>
                        </div>
                    <% end %>
                </div>        
            </div>    
        </div>
    </div>
</div>

app/views/rooms/description.html.erb
<div class="container mt-3 pb-4">
    <div class="row">
        <div class="col-md-3">
         <%= render "rooms/sidebar"%>
        </div>
        <div class="col-md-4">
            <div class="card mt-3" style="width: 50rem;">
                <strong><div class="card-header bg-success text-light">
                    Description
                </div><strong>
                <div class="p-4">
                    <%= form_for @room do |f| %>
                        <div class="form-group">
                            <%= f.label :Listingname %>
                            <p><%= f.text_field :name, placeholder: "What is your listing name", class:"form-control" %></p>
                        </div>
                        <div class="form-group">
                            <%= f.label :Summary %>
                            <%= f.text_area :summary, rows: 5, placeholder: "Sammary of your house", class: "form-control" %>
                        </div>
                        <div class="row">
                            <%= f.submit "Save", class: "btn btn-outline-success my-2 my-sm-0 ml-3" %>
                        </div>
                    <% end %>
                </div>        
            </div>    
        </div>
    </div>
</div>

app/views/rooms/index.html.erb
<div class=" container editprofile mt-2 pb-4">
    <div class="row">
        <div class="col-md-4">
            <%= render "reservations/sidebar"%>
        </div>
        <div class="col-md-4">
            <div class="card mt-3" style="width: 50rem;">
                <strong><div class="card-header bg-success text-light text-center"></strong>
                    Your Listing
                </div>
                <div class="card-body">
                    <% @rooms.each do |room| %>
                        <% if room.photos.any? %>
                            <%= image_tag room.photos.first.image.url, class: "mr-5 profile_picture_index" %>
                        <% else %>
                            <%= image_tag "no-image.png", class: "mr-5 profile_picture_index2"  %>
                        <% end %>
                        <%= link_to room.name, room_path(room) %>
                        <%= link_to "Upload", listing_room_path(room),  class: "btn btn-outline-success my-2 my-sm-0 float-right" %>
                        <div class="border-bottom my-3"></div>
                    <% end %>   
                </div>  
                <div class="pagenate mt-1 text-center"><%= will_paginate %></div>   
            </div>  
        </div>
    </div>
</div>

app/views/rooms/listing.html.erb
<div class="container  mt-3 pb-4">
    <div class="row">
        <div class="col-md-3">
        <%= render "rooms/sidebar"%>
        </div>
        <div class="col-md-4">
            <div class="card mt-3" style="width: 50rem;">
                <strong>
                    <div class="card-header bg-success text-light">
                        Listing
                    </div>
                <strong>
                <div class="p-3">
                    <div class="p-3">
                        <%= form_for @room do |f| %>
                            <div class="row">
                                <div class="col-4 select">
                                    <%= f.label :Home_Type %>
                                    <p><%= f.select :home_type, [["Apartment","Apartment"], ["House","House"], ["Bed & Breakfast","Bed & Breakfast"]], prompt: "select...", class:"form-control" %></p>
                                </div>
                                <div class="col-4 select">
                                    <%= f.label :Room_Type %>
                                    <p><%= f.select :room_type, [["Entire","Entire"], ["Private","Private"], ["Shared","Shared"]], prompt: "select...", class:"form-control" %></p>
                                </div>
                                <div class="col-4 select">
                                    <%= f.label :Accommodate %>
                                    <p><%= f.select :gest_count, [["1",1], ["2",2], ["3",3], ["4+",4]], prompt: "select...", class:"form-control" %></p>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-4 select">
                                    <%= f.label :Bedrooms %>
                                    <p><%= f.select :bedroom_count, [["1",1], ["2",2], ["3",3], ["4+",4]], prompt: "select...", class:"form-control" %></p>
                                </div>
                                <div class="col-4 select">
                                    <%= f.label :Bathrooms %>
                                    <p><%= f.select :bathroom_count, [["1",1], ["2",2], ["3",3], ["4+",4]], prompt: "select...", class:"form-control" %></p>
                                </div>
                            </div>
                            <div class="row">
                                <%= f.submit "Save", class: "btn btn-outline-success my-2 my-sm-0 ml-3" %>
                            </div>
                        <% end %>
                    </div>    
                </div>    
            </div>   
        </div>
    </div>
</div>

app/views/rooms/location.html.erb
<div class="container  mt-3 pb-4">
    <div class="row">
        <div class="col-md-3">
        <%= render "rooms/sidebar"%>
        </div>
        <div class="col-md-4">
            <div class="card mt-3" style="width: 50rem;">
                <strong>
                    <div class="card-header bg-success text-light">
                    Location
                    </div>
                <strong>
                <div class="p-3">
                    <div class="p-3">
                        <%= form_for @room do |f| %>
                            <div class="">
                                <%= f.label :Address %>
                                <p><%= f.text_field :address, placeholder: "What is the address?", class:"form-control" %></p>
                            </div>
                            <div class="row">
                                <%= f.submit "Save", class: "btn btn-outline-success my-2 my-sm-0 ml-3" %>
                            </div>
                        <% end %>
                    </div>
                </div>
            </div>    
        </div>
    </div>
</div>

app/views/rooms/new.html.erb
<div class="container mt-3 pb-4">
    <div class="col-md-12">
        <div class="card mt-5">
            <strong>
                <div class="card-header bg-success text-light text-center">
                    Create your beautiful place
                </div>
                <div class="p-3">
                    <%= form_for @room do |f| %>
                        <div class="row">
                            <div class="col-4 select">
                                <%= f.label :Home_Type %>
                                <p><%= f.select :home_type, [["Apartment","Apartment"], ["House","House"], ["Bed & Breakfast","Bed & Breakfast"]], prompt: "select...", class:"form-control" %></p>
                            </div>
                            <div class="col-4 select">
                                <%= f.label :Room_Type %>
                                <p><%= f.select :room_type, [["Entire","Entire"], ["Private","Private"], ["Shared","Shared"]], prompt: "select...", class:"form-control" %></p>
                            </div>
                            <div class="col-4 select">
                                <%= f.label :Accommodate %>
                                <p><%= f.select :gest_count, [["1",1], ["2",2], ["3",3], ["4+",4]], prompt: "select...", class:"form-control" %></p>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-4 select">
                                <%= f.label :Bedrooms %>
                                <p><%= f.select :bedroom_count, [["1",1], ["2",2], ["3",3], ["4+",4]], prompt: "select...", class:"form-control" %></p>
                            </div>
                            <div class="col-4 select">
                                <%= f.label :Bathrooms %>
                                <p><%= f.select :bathroom_count, [["1",1], ["2",2], ["3",3], ["4+",4]], prompt: "select...", class:"form-control" %></p>
                            </div>
                        </div>
                        <div class="row">
                            <%= f.submit "Create rooms", class: "btn btn-outline-success my-2 my-sm-0 ml-3" %>
                        </div>
                    <% end %>
                </div> 
            </strong>   
        </div>   
    </div>
</div>

app/views/rooms/photo.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-3">
            <%= render "rooms/sidebar"%>
        </div>
        <div class="col-md-4">
            <div class="card mt-3" style="width: 50rem;">
                <strong>
                    <div class="card-header bg-success text-light">
                        Photo
                    </div>
                <strong>
                <div class="p-3">
                    <div class="p-3">
                        <%= form_for @room, url: room_photos_path(@room), method: 'post', html: {multipart: true} do |f| %>
                            <div class="row">
                                <div class="col-md-6 offset-md-4">
                                    <%= file_field_tag "images[]", type: :file, multiple: true, class: "" %>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6 offset-md-4 mt-3">
                                    <%= f.submit "Add Photos", class: "btn btn-outline-success my-2 my-sm-0 ml-3" %>
                                </div>
                            </div>
                        
                        <% end %>
                        <div class="border-bottom my-3"></div>
                        <%= render "photos/photo_list" %>
                    </div>    
                </div>    
            </div>   
        </div>
    </div>
</div>

app/views/rooms/photo_upload.html.erb
<div class="container  mt-3 pb-4">
    <div class="row">
        <div class="col-md-3">
            <%= render "rooms/sidebar"%>
        </div>
        <div class="col-md-4">
            <div class="card mt-3" style="width: 50rem;">
                <strong>
                    <div class="card-header bg-success text-light">
                        Photo
                    </div>
                <strong>
                <div class="p-3">
                    <%= form_for @room, url: room_photos_path(@room), method: 'post', html: {multipart: true} do |f| %>
                        <div class="row">
                            <div class="col-md-4 offset-md-4 mt-3">
                                <%= label_tag "images[]", "Select Photos", class: "btn btn-outline-success my-2 my-sm-0 ml-5"%>
                                <%= file_field_tag "images[]", type: :file, multiple: true, class: "image_form" %>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-3 offset-md-4 mt-3">
                                <%= f.submit "Add Photos", class: "btn btn-outline-success add_photos my-2 my-sm-0 px-3" %>
                            </div>
                        </div>
                    
                    <% end %>
                    <div class="border-bottom my-3"></div>
                    <div id = "photos">
                        <%= render "photos/photos_list" %>
                    </div> 
                </div>    
            </div>   
        </div>
    </div>
</div>

app/views/rooms/price.html.erb
<div class="container mt-3 pb-4">
    <div class="row">
        <div class="col-md-3">
            <%= render "rooms/sidebar"%>
        </div>
        <div class="col-md-4">
            <div class="card mt-3" style="width: 50rem;">
                <strong>
                    <div class="card-header bg-success text-light">
                        Price
                    </div>
                <strong>
                <div class="p-3">
                    <div class="p-3">
                        <%= form_for @room do |f| %>
                            <div class="price">
                                <%= f.label :Price %>
                                <p><%= f.text_field :price, placeholder: "eg: $100", class:"form-control" %></p>
                            </div>
                            <div class="row">
                                <%= f.submit "Save", class: "btn btn-outline-success my-2 my-sm-0 ml-3" %>
                            </div>
                        <% end %>
                    </div>
                </div>
            </div>    
        </div>
    </div>
</div>