config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  devise_for :users,
    path: '',
    path_names: {sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'registration'},
    controllers: {omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations'}

  resources :rooms do 
    member do
      get 'listing'
      get 'price'
      get 'description'
      get 'photo_upload'
      get 'amenity'
      get 'location'
      get 'preload'
      get 'preview'
    end
    resources :photos, only: [:create, :destroy]
    resources :reservations, only: [:create]
  end

  get '/reservations', to: "reservations#your_reservations"
  get '/trips', to:"reservations#your_trips"

  resources :users, only: [:show]

  resources :guest_reviews, only: [:create, :destroy]
  resources :host_reviews, only: [:create, :destroy]

  get 'search' => 'pages#search'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :room

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def create
    @room = Room.find(params[:room_id])

    if params[:images]
      params[:images].each do |img|
        @room.photos.create(image: img) #create photo and save to db
      end

      @photos = @room.photos #get 
      redirect_back(fallback_location: request.referer, notice: "Saved...")
    end
  end

      # def destroy
    #   @photo = Photo.find(params[:id])
    #   @photo.destroy
      
    #   redirect_back(fallback_location: request.referer, notice: "Saved...")
    #   end

  def destroy
    @photo = Photo.find(params[:id])
    room = @photo.room

    @photo.destroy
    @photos = Photo.where(room_id: room.id)

    respond_to :js

  end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_photo_list.html.erb
<div class="row">
    <% if @photos.count > 0 %>
        <% @photos.each do |photo| %>
            <div class="col-4">
                <div class="card">
                    <%= image_tag photo.image.url, class: "card-img-top" %>
                    <div class="card-body">
                        <%= link_to room_photo_path(photo.room_id, photo), remote: true, method: :delete, data: {confirm: "Are you sure?"} do %>
                            <i class="fa fa-trash float-right"></i> 
                        <% end %>
                    </div>
                </div>
            </div>
        <% end %>
    <% end %>
</div>

app/views/photos/_photos_list.html.erb
<div class="row">
    <% if @photos.count > 0 %>
        <% @photos.each do |photo| %>
            <div class="col-4">
                <div class="card">
                    <%= image_tag photo.image.url, class: "card-img-top" %>
                    <div class="card-body">
                        <%= link_to room_photo_path(photo.room_id, photo), remote: true, method: :delete, data: {confirm: "Are you sure?"} do %>
                            <i class="fa fa-trash float-right"></i> 
                        <% end %>
                    </div>
                </div>
            </div>
        <% end %>
    <% end %>
</div>

app/views/photos/destoy.js.erb
$("#photos").html("<%= j render 'photos_list' %>");

app/views/photos/destroy.js.erb
$("#photos").html("<%= j render 'photos_list' %>");