config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  devise_for :users,
    path: '',
    path_names: {sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'registration'},
    controllers: {omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations'}

  resources :rooms do 
    member do
      get 'listing'
      get 'price'
      get 'description'
      get 'photo_upload'
      get 'amenity'
      get 'location'
      get 'preload'
      get 'preview'
    end
    resources :photos, only: [:create, :destroy]
    resources :reservations, only: [:create]
  end

  get '/reservations', to: "reservations#your_reservations"
  get '/trips', to:"reservations#your_trips"

  resources :users, only: [:show]

  resources :guest_reviews, only: [:create, :destroy]
  resources :host_reviews, only: [:create, :destroy]

  get 'search' => 'pages#search'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="border-top fixed-bottom">
    <div class="col-12">
        <div class="container">                    
            <div class="row">
                <div class="col-4 text-left text-secondary">
                © ︎All right reserved
                </div>
                <div class="col-8 text-right text-secondary">
                    <i class="fa fa-facebook-square"></i>
                    <i class="fa fa-twitter-square"></i>
                    <i class="fa fa-instagram"></i>
                </div>
            </div>
        </div>
    </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-sm navbar-light header">
    <div class="container">
        <%= link_to "Home", root_path, class: "navbar-brand" %>
        <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        </form>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="ml-auto">
            <div class="collapse navbar-collapse nav-item" id="navbarSupportedContent">
                <ul class="navbar-nav nav-item">
                    <% if user_signed_in? %>
                        <div class="nav-item mr-2">
                            <%= link_to "Become a host", new_room_path(current_user),  class: "btn btn-outline-success mt-2" %>
                        </div>
                        <div class="nav-item mr-2">
                            <%= image_tag avatar_url(current_user), class: "rounded-circle profile_picture" %>
                        </div>
                        <div class="nav-item mr-5 mt-1">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <%= current_user.name %>
                                </a>
                            <li class="nav-item dropdown">
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <%= link_to "Manage Listing ", rooms_path, class: "dropdown-item" %>
                                    <a class="dropdown-item" href="https://airbnb-yusuke.herokuapp.com/rooms">List Your Space</a>
                                    <a class="dropdown-item" href="https://airbnb-yusuke.herokuapp.com/reservations">Your Reservations</a>
                                    <a class="dropdown-item" href="https://airbnb-yusuke.herokuapp.com/trips">Your Trips</a>
                                        <div class="dropdown-divider"></div>
                                    <%= link_to "Edit Profile", edit_user_registration_path, class: "dropdown-item" %>
                                    <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
                                </div>
                            </li>
                        </div>    
                    <% else %>
                        <div class="nav-item">
                            <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %></a>
                        </div>
                        <div class="nav-item">
                            <%= link_to "Login", new_user_session_path, class: "nav-link" %></a>
                        </div>
                    <% end %>
                </ul>
            </div>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
    <title>AirbnbYusuke</title>
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
        <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    </head>

    <body>
        <%= render "layouts/header" %>

        <%# <p class="notice"><%= notice %>
        <%# <p class="alert"><%= alert %>
        <%= render "shared/message" %>
        <%= yield %>
        <%= render "layouts/footer" %>
    </body>
</html>